const observer = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (!entry.isIntersecting) return;
    entry.target.classList.add('visible');
    observer.unobserve(entry.target);
  });
}, { threshold: 0.12 });

document.querySelectorAll('.reveal').forEach(el => observer.observe(el));

const counterObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (!entry.isIntersecting) return;
    const el = entry.target;
    const end = Number(el.dataset.count);
    const start = performance.now();
    const run = now => {
      const progress = Math.min((now - start) / 1300, 1);
      el.textContent = Math.round(end * (1 - Math.pow(1 - progress, 3)));
      if (progress < 1) requestAnimationFrame(run);
    };
    requestAnimationFrame(run);
    counterObserver.unobserve(el);
  });
}, { threshold: 0.6 });

document.querySelectorAll('[data-count]').forEach(el => counterObserver.observe(el));

const services = document.querySelectorAll('.service');
services.forEach(service => service.addEventListener('mouseenter', () => {
  services.forEach(item => item.classList.remove('active'));
  service.classList.add('active');
}));

const glow = document.querySelector('.cursor-glow');
window.addEventListener('pointermove', e => {
  glow.style.left = `${e.clientX}px`;
  glow.style.top = `${e.clientY}px`;
});

const menuButton = document.querySelector('.menu-btn');
menuButton.addEventListener('click', () => {
  const open = menuButton.getAttribute('aria-expanded') === 'true';
  menuButton.setAttribute('aria-expanded', String(!open));
  document.querySelector('.site-header nav').classList.toggle('mobile-open');
});

const clientTrack = document.getElementById('clientTrack');
if (clientTrack) {
  const clients = [
    ['Dubai Holding','dubai-holding-300x211.png'],['Samsung C&T','samsung-logo-300x200.png'],['Lootah','lootah.png'],['Itqan','itqan-300x284.jpg'],['PLUS','PLUS.jpg'],['ENGIE Lab','engie-lab-logo.png'],['Sharjah Airport','Sharjah_Airport_logo.svg_-300x286.png'],['BHG','BHG_logo-294x300.jpg'],['SPD','spd-300x300.jpg'],['Binghatti','binghatti-300x300.png'],['QatarEnergy','QatarEnergy_logo.svg_-290x300.png'],['Samsung','samsung-logo-1-300x300.jpg'],['Accord','accord.jpg'],['Smart Cookie','smart-cookie-300x200.png'],['Jacobs','JACOBS-300x200.png'],['Restore UAE','restoreuae_logo.jpg'],['Perfect Maintenance','perfect-maint.jpg'],['MAI','mai-logo-300x200.jpg'],['ServeU','serveu.jpg'],['Kramer Albrecht','KRAMERALBRECHT-LOGO-LINKEDIN.png'],['LS','ls-300x200.jpg']
  ];
  const markup = clients.map(([name,file]) => `<div class="client-logo"><img src="assets/clients/${file}" alt="${name}" loading="lazy"></div>`).join('');
  clientTrack.innerHTML = markup + markup;
  clientTrack.querySelectorAll('.client-logo:nth-child(n+22)').forEach(item => item.setAttribute('aria-hidden','true'));
}

const serviceData = {
  'condition-assessment': { title:'Condition Assessment', category:'Existing structures', summary:'Establishing the true condition of a structure through objective inspection and testing.', lead:'A durable intervention begins with a reliable understanding of what is actually happening inside the structure.', body:'CDE combines systematic visual survey with targeted non-destructive and intrusive testing to map deterioration, quantify its extent and distinguish symptoms from underlying causes. Findings are translated into a clear engineering report designed to support confident technical and commercial decisions.', points:[['Visual condition survey','Systematic mapping of defects, distress and deterioration.'],['Non-destructive testing','Evidence-led investigation with minimal disruption.'],['Condition mapping','Clear records of defect location, extent and severity.'],['Actionable reporting','Prioritized findings and technically grounded next steps.']] },
  'forensic-investigation': { title:'Forensic Investigation', category:'Existing structures', summary:'Finding the mechanisms behind cracking, corrosion, defects and premature deterioration.', lead:'Treating the visible defect without identifying its cause often leads to repeated failure.', body:'Our forensic investigations connect site evidence, material behaviour, exposure conditions and structural performance. CDE develops and tests engineering hypotheses until the deterioration mechanism is understood, allowing the response to address the cause rather than only the symptom.', points:[['Root-cause analysis','Evidence organized into a defensible diagnosis.'],['Crack assessment','Severity, activity and durability implications.'],['Corrosion investigation','Reinforcement condition and exposure mechanisms.'],['Material evaluation','Testing and interpretation of in-place properties.']] },
  'structural-assessment': { title:'Structural Assessment & Strengthening', category:'Existing structures', summary:'Evaluating capacity and designing strengthening for changing performance demands.', lead:'When loading, use or condition changes, the remaining capacity of the structure must be established with confidence.', body:'CDE reviews available records, confirms the as-built condition, evaluates material properties and develops analytical models appropriate to the question at hand. Where intervention is needed, strengthening solutions are selected for technical effectiveness, constructability and compatibility with the existing structure.', points:[['Capacity evaluation','Verification against current or proposed demands.'],['As-built verification','Geometry and reinforcement confirmed where required.'],['Strengthening design','Targeted enhancement of structural performance.'],['Constructability review','Solutions developed for real site constraints.']] },
  'repair-rehabilitation': { title:'Repair & Rehabilitation', category:'Existing structures', summary:'Cause-led repair strategies, specifications, supervision and quality control.', lead:'A repair is only durable when its materials and methodology match the deterioration mechanism and exposure environment.', body:'CDE develops repair concepts into coordinated specifications and drawings, supports contractor selection, and remains engaged during execution. Site supervision and QA/QC verify preparation, materials, application and acceptance so that the built repair performs as designed.', points:[['Repair strategy','Options assessed against performance and lifecycle value.'],['Specifications','Clear materials, methods and acceptance criteria.'],['Site supervision','Engineering continuity through execution.'],['QA/QC','Verification of preparation, application and outcome.']] },
  'durability-engineering': { title:'Durability Engineering', category:'New structures', summary:'Designing service life, protection and predictable performance into new construction.', lead:'The most cost-effective time to secure durability is while specifications, detailing and protection systems can still be shaped.', body:'CDE translates exposure conditions and intended service life into practical design requirements. Our work can include durability planning, cover and material specifications, thermal modelling, service-life prediction and construction-stage defect evaluation.', points:[['Durability planning','Exposure-led design requirements from day one.'],['Service-life prediction','Performance modeled under actual exposure.'],['Thermal modelling','Early-age temperature and cracking risk.'],['Construction review','Defects identified before they compromise performance.']] },
  'corrosion-investigation': { title:'Corrosion Investigation', category:'Existing structures', summary:'Identifying reinforcement deterioration and the mechanisms driving it.', lead:'Corrosion can remain concealed until cracking and spalling make the problem visible.', body:'CDE combines field observations, electrochemical testing, sampling and exposure assessment to establish where corrosion is active, how extensive it is and what mechanism is responsible. This evidence sets the basis for proportionate repair and protection.', points:[['Potential mapping','Locating areas of likely corrosion activity.'],['Chloride assessment','Determining contamination profiles and risk.'],['Carbonation testing','Evaluating loss of reinforcement protection.'],['Repair zoning','Defining rational, evidence-based intervention areas.']] },
  'crack-concrete-assessment': { title:'Crack & Concrete Assessment', category:'Existing structures', summary:'Determining crack severity, origin and structural or durability implications.', lead:'Not every crack has the same meaning—and the right response depends on its cause and behaviour.', body:'CDE documents crack patterns, measures dimensions and activity, evaluates likely mechanisms and relates them to structural form, loading, restraint and material behaviour. Concrete defects such as honeycombing and poor compaction are assessed alongside their effect on performance.', points:[['Crack mapping','Pattern, width and distribution recorded clearly.'],['Movement monitoring','Activity evaluated where needed.'],['Concrete evaluation','Defect depth, extent and implications.'],['Repair guidance','Intervention matched to cause and risk.']] },
  'specialist-assessment': { title:'Fire, PT & Thermographic Assessment', category:'Existing structures', summary:'Specialist investigation of hidden defects, post-tensioned systems and fire damage.', lead:'Some of the most consequential defects cannot be assessed reliably by conventional visual inspection alone.', body:'CDE applies specialist investigation techniques suited to the structural system and event. This can include post-fire material evaluation, post-tensioned tendon assessment and thermographic scanning to identify concealed anomalies and target further investigation.', points:[['Fire damage','Material and structural effects following heat exposure.'],['PT systems','Condition evaluation of tendons and anchorage zones.'],['Thermography','Rapid detection of concealed discontinuities.'],['Targeted verification','Follow-up testing directed by initial findings.']] },
  'repair-supervision': { title:'Repair Supervision & QA/QC', category:'Existing structures', summary:'Ensuring specified repairs are delivered correctly on site.', lead:'Even a technically sound repair design depends on disciplined preparation and execution.', body:'CDE provides engineering supervision through critical stages, reviews materials and method statements, witnesses trials and testing, and documents compliance. Issues are resolved while work is accessible, protecting the performance of the completed intervention.', points:[['Method review','Work sequence and materials checked before execution.'],['Hold points','Critical stages inspected before concealment.'],['Quality records','Evidence organized for acceptance and handover.'],['Technical resolution','Site issues addressed with design intent intact.']] },
  'lifecycle-planning': { title:'Maintenance & Lifecycle Planning', category:'Existing structures', summary:'Planned interventions that protect structural performance and investment.', lead:'Proactive maintenance converts deterioration from an emergency into a manageable lifecycle decision.', body:'CDE uses condition, exposure, consequence and rate of deterioration to prioritize future inspections and maintenance. The resulting plan helps asset owners direct budgets toward the right interventions at the right time.', points:[['Risk prioritization','Attention focused where consequence and likelihood meet.'],['Inspection planning','Intervals and scopes aligned to asset condition.'],['Maintenance roadmap','Actions staged across practical time horizons.'],['Lifecycle value','Capital directed toward durable performance.']] },
  'durability-planning': { title:'Durability Planning', category:'New structures', summary:'Exposure-class design, cover specification and protection strategy.', lead:'Durability requirements must reflect the environment a structure will actually experience.', body:'CDE develops the design basis for durability by defining exposure zones, deterioration risks, material parameters, cover, crack control and protection measures. Requirements are coordinated into project documents so they can be procured and verified.', points:[['Exposure zoning','Environmental conditions mapped across the asset.'],['Material criteria','Concrete and protection requirements defined.'],['Detail review','Durability risks resolved at interfaces.'],['Compliance framework','Inspection and testing requirements established.']] },
  'service-life-prediction': { title:'Service-Life Prediction', category:'New structures', summary:'Modelling structural performance under real exposure conditions.', lead:'Service-life modelling connects design choices to long-term performance.', body:'CDE uses appropriate deterioration models, project material data and environmental assumptions to test whether proposed designs meet their intended service life. Options can be compared before construction commits the project to a long-term outcome.', points:[['Performance modelling','Deterioration forecast against target service life.'],['Sensitivity analysis','Critical assumptions and variables identified.'],['Option comparison','Protection strategies assessed consistently.'],['Design optimization','Performance balanced with buildability and cost.']] },
  'thermal-modeling': { title:'Thermal Modeling', category:'New structures', summary:'Predicting temperature-driven stress and early-age cracking risk.', lead:'In mass concrete, heat generation and restraint can create cracking before the structure enters service.', body:'CDE models temperature development, gradients, restraint and tensile strain to assess early-age cracking risk. Findings inform pour geometry, mix performance, cooling, insulation and construction sequencing.', points:[['Temperature prediction','Heat development through placement and curing.'],['Restraint assessment','Internal and external restraint considered.'],['Crack-risk evaluation','Thermal strain checked against material capacity.'],['Control measures','Practical construction measures specified.']] },
  'defect-evaluation': { title:'Construction Defect Evaluation', category:'New structures', summary:'Early assessment of honeycombing, poor curing and early-age cracking.', lead:'Construction defects are most effectively addressed before they are concealed or allowed to affect long-term durability.', body:'CDE assesses the location, extent and significance of observed defects, defines any further investigation needed and recommends acceptance, monitoring or repair. Decisions remain proportionate to actual performance risk.', points:[['Defect survey','Extent and characteristics documented.'],['Impact assessment','Structural and durability significance evaluated.'],['Acceptance criteria','Clear basis for technically sound decisions.'],['Remedial guidance','Targeted repair where intervention is warranted.']] }
};

Object.assign(serviceData, {
  'crack-assessment':{title:'Crack Assessment',category:'Existing structures',summary:'Diagnosis of cracking—its cause, activity and structural significance—with targeted remedial guidance.',lead:'Not every crack is harmful. The essential task is distinguishing stable, cosmetic cracking from an active symptom of a deeper problem.',body:'CDE examines crack patterns, classifies the cracking, traces its root cause and evaluates its structural implications. The assessment turns an ambiguous visible symptom into an evidence-based decision on whether the crack should be repaired, monitored or recorded.',points:[['Crack survey','Pattern, width and distribution documented.'],['Classification','Type and likely mechanism established.'],['Root-cause analysis','Structural, thermal and material factors considered.'],['Remedial guidance','Repair, monitoring or recording defined.']]},
  'concrete-evaluation':{title:'Concrete Evaluation',category:'Existing and new structures',summary:'Independent evaluation of concrete quality and construction defects before they compromise long-term performance.',lead:'Improper curing, honeycombing and early-age cracking can quietly compromise durability if they are not identified and corrected in time.',body:'CDE provides an objective, evidence-based view of the concrete actually delivered. Visual inspection, quality assessment, targeted testing and defect analysis are combined to define practical corrective measures and confirm alignment with design requirements.',points:[['Visual inspection','Cracks, voids and honeycombing identified.'],['Quality assessment','Workmanship and construction practices reviewed.'],['Testing','Strength, uniformity and integrity verified.'],['Corrective action','Practical measures defined from the evidence.']]},
  'fire-damage':{title:'Fire Damage Assessment',category:'Existing structures',summary:'Evidence-led evaluation of material and structural performance following fire exposure.',lead:'Visible damage alone cannot establish how a fire-affected structure will behave under future loading.',body:'CDE evaluates the effect of elevated temperatures on concrete, steel and structural elements, quantifies the damage and establishes whether targeted repair, strengthening or replacement is appropriate. The outcome is a defensible basis for safe and economical restoration.',points:[['Damage survey','Exposure and visible effects documented.'],['Material evaluation','Heat-related property changes assessed.'],['Structural review','Remaining performance evaluated.'],['Recovery strategy','Repair, strengthening or replacement defined.']]},
  'thermographic-inspection':{title:'Thermographic Inspection',category:'Existing structures',summary:'Infrared imaging that reveals hidden moisture, insulation failures and energy loss without touching the structure.',lead:'Some damaging building defects remain concealed behind façades, roofs and finishes for years.',body:'CDE uses calibrated thermal imaging as a rapid, non-destructive diagnostic tool. Engineers interpret temperature patterns in the context of construction and environmental conditions, distinguish genuine anomalies from thermal noise, and document findings with annotated images.',points:[['Infrared survey','Surface temperature differences captured.'],['Interpretation','Anomalies separated from normal variation.'],['Defect mapping','Moisture, insulation and energy issues located.'],['Reporting','Annotated thermal evidence clearly explained.']]},
  'pt-structure':{title:'PT Structure Assessment',category:'Existing structures',summary:'Specialist evaluation of post-tensioned tendons, anchorages and structural behaviour.',lead:'Post-tensioned systems are efficient but uniquely demanding to assess because their critical, highly stressed components are concealed.',body:'CDE combines targeted inspection and testing with rigorous structural analysis to evaluate tendon and anchorage condition and the behaviour they govern. The work gives owners an evidence-based understanding of post-tensioned structural performance and any remedial need.',points:[['System review','PT layout and available records assessed.'],['Targeted investigation','Concealed components examined appropriately.'],['Structural analysis','Performance and capacity evaluated.'],['Remedial guidance','Risk-based next steps defined.']]},
  'building-audit':{title:'Building Condition Audit',category:'Existing structures',summary:'A systematic, risk-based evaluation that provides a clear basis for maintenance decisions.',lead:'Buildings deteriorate gradually through exposure, use and age; structured evaluation is the reliable way to stay ahead of that curve.',body:'CDE systematically inspects structural and related elements, identifies and classifies defects, evaluates component condition and prioritizes risk. Findings become a structured maintenance roadmap so owners can direct investment where it matters most.',points:[['Element inspection','Cracks, spalling, leakage and distress recorded.'],['Defect classification','Findings grouped by type and severity.'],['Risk evaluation','Safety, performance and durability prioritized.'],['Maintenance plan','Practical actions organized for decision-making.']]},
  'as-built-drawings':{title:'As-Built Drawings Preparation',category:'Existing structures',summary:'Accurate drawings that record the true dimensions, layout and structural details of a completed structure.',lead:'Reliable assessment, repair and future modification depend on documentation that reflects what was actually built.',body:'CDE prepares plans, sections and elevations from disciplined site measurement and data collection. Engineer-led verification ensures the completed drawings provide owners, consultants and facility managers with a dependable technical reference.',points:[['Site measurement','Existing dimensions and conditions captured.'],['Data collection','Structural and architectural information gathered.'],['Drawing preparation','Accurate plans, sections and elevations produced.'],['Verification','Completeness and precision checked before issue.']]},
  'durability-assessment':{title:'Durability & Service Life Assessment',category:'Existing and new structures',summary:'Evaluation and prediction of how a structure will perform under its real environmental and operational conditions.',lead:'Middle East temperatures, chlorides and aggressive exposure make durability a property to evaluate and quantify—not assume.',body:'CDE combines condition insight with forward-looking performance analysis to evaluate current durability and forecast service life. This gives owners, developers and consultants a clearer basis for early decisions before deterioration becomes costly repair.',points:[['Exposure assessment','Environmental and operational demands defined.'],['Current durability','Material condition and resistance evaluated.'],['Service-life modelling','Future performance predicted.'],['Decision support','Protection and intervention options compared.']]},
  'maintenance-planning':{title:'Maintenance Planning & Lifecycle Management',category:'Existing and new structures',summary:'Organized monitoring, upkeep and restoration strategies calibrated to asset condition and exposure.',lead:'A considered maintenance plan turns reactive spending into a controlled programme that protects value over decades.',body:'CDE develops forward-looking maintenance and lifecycle strategies around existing condition, deterioration risk and operational requirements. Owners gain a practical basis for deciding what to inspect, maintain or repair—and when.',points:[['Condition baseline','Current asset needs established.'],['Monitoring plan','Inspection scope and frequency defined.'],['Intervention priorities','Actions ranked by risk and value.'],['Lifecycle roadmap','Spending organized across time horizons.']]},
  'repair-design':{title:'Repair Design & Specifications',category:'Existing structures',summary:'Evidence-led repair schemes that restore performance, durability and serviceability.',lead:'A repair that treats visible symptoms without addressing their cause is likely to fail again.',body:'CDE grounds every repair strategy in condition assessment and root-cause analysis. The resulting drawings, specifications and method requirements give owners, consultants and contractors an unambiguous, product-neutral basis for durable remedial works.',points:[['Repair strategy','Options matched to deterioration mechanism.'],['Design drawings','Buildable remedial details developed.'],['Specifications','Materials, preparation and acceptance defined.'],['Method requirements','Execution aligned to design intent.']]}
});

const serviceSlugByTitle = {
  'Condition Assessment':'condition-assessment','Forensic Investigation':'forensic-investigation','Structural Assessment':'structural-assessment','Structural Assessment & Strengthening':'structural-assessment','Repair & Rehabilitation':'repair-rehabilitation','Repair Design & Specifications':'repair-design','Durability Engineering':'durability-engineering','Corrosion Investigation':'corrosion-investigation','Crack Assessment':'crack-assessment','Concrete Evaluation':'concrete-evaluation','Fire Damage Assessment':'fire-damage','Thermographic Inspection':'thermographic-inspection','PT Structure Assessment':'pt-structure','Building Condition Audit':'building-audit','As-Built Drawings Preparation':'as-built-drawings','Repair Supervision & QA/QC':'repair-supervision','Maintenance & Lifecycle Planning':'maintenance-planning','Maintenance Planning & Lifecycle Management':'maintenance-planning','Durability Planning':'durability-planning','Durability & Service Life Assessment':'durability-assessment','Service-Life Prediction':'durability-assessment','Thermal Modeling':'thermal-modeling','Construction Defect Evaluation':'concrete-evaluation'
};

document.querySelectorAll('.service, .capability-list article').forEach(card => {
  const title = card.querySelector('h3')?.textContent.trim();
  const slug = serviceSlugByTitle[title];
  if (!slug) return;
  card.classList.add('is-linked'); card.tabIndex = 0; card.setAttribute('role','link');
  card.setAttribute('aria-label', `Learn more about ${title}`);
  if (card.matches('.capability-list article')) { const arrow=document.createElement('span'); arrow.className='cap-arrow'; arrow.textContent='↗'; card.appendChild(arrow); }
  const go = () => window.location.href = `service-detail.html?service=${slug}`;
  card.addEventListener('click', go); card.addEventListener('keydown', e => { if(e.key==='Enter'||e.key===' ') go(); });
});

const projectData = {
  'trillionaire-residences':{title:'Trillionaire Residences',location:'Dubai, UAE',category:'assessment',image:'https://cde-me.com/wp-content/uploads/2026/03/Trillionaire_Residences_by_Binghatti_.jpg',summary:'Condition assessment and repair design for a luxury high-rise development.',lead:'An objective assessment translated observed conditions into a focused repair strategy for a prominent Dubai residential development.',body:'CDE evaluated the building condition, investigated relevant deterioration and developed engineering recommendations suited to the structure and its operational context. The assignment connected diagnosis to implementable repair decisions, giving the project team a clear technical basis for action.',points:[['Service','Condition assessment'],['Outcome','Repair design guidance'],['Asset','Luxury residential high-rise'],['Region','Dubai, UAE']]},
  'serenia-residences':{title:'Serenia Residences',location:'Palm Jumeirah, Dubai',category:'rehabilitation',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-15.jpg',summary:'Corrosion investigation and rehabilitation for a coastal residential development.',lead:'Marine exposure demands a clear understanding of corrosion mechanism and extent before rehabilitation begins.',body:'CDE investigated reinforcement corrosion and associated deterioration within the context of the development’s coastal exposure. Findings informed a targeted rehabilitation approach focused on controlling the cause, restoring affected areas and supporting longer-term performance.',points:[['Service','Corrosion investigation'],['Outcome','Rehabilitation strategy'],['Asset','Residential development'],['Region','Palm Jumeirah, Dubai']]},
  'injaz-building':{title:'Injaz Building',location:'Dubai, UAE',category:'assessment',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-13d.jpg',summary:'Forensic investigation and structural analysis.',lead:'Forensic evidence and structural analysis were combined to clarify the building’s condition and performance.',body:'CDE developed an evidence-led assessment around the observed concerns, using investigation findings to direct structural analysis and engineering judgment. The resulting conclusions were organized so stakeholders could understand the issue, its significance and the appropriate next action.',points:[['Service','Forensic investigation'],['Outcome','Structural analysis'],['Asset','Building structure'],['Region','Dubai, UAE']]},
  'west-f5-building':{title:'West F5 Building',location:'Dubai, UAE',category:'assessment',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-6a.jpg',summary:'Structural assessment and strengthening design.',lead:'Existing capacity was evaluated and translated into a practical strengthening response.',body:'CDE assessed the structural system against the required performance demands, identified areas requiring enhancement and developed strengthening measures compatible with the existing building. The design balanced analytical requirements with the constraints of implementation.',points:[['Service','Structural assessment'],['Outcome','Strengthening design'],['Asset','Existing building'],['Region','Dubai, UAE']]},
  'seawater-intake':{title:'Seawater Intake Pumping Station',location:'Fujairah, UAE',category:'durability',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-10.jpg',summary:'Durability engineering in an aggressive marine environment.',lead:'Critical infrastructure in direct marine exposure requires durability measures designed around severe, continuous environmental demand.',body:'CDE applied specialist durability engineering to the pumping station’s aggressive seawater environment. Exposure, deterioration risk and long-term performance requirements were considered together to guide protection and lifecycle decisions for this critical asset.',points:[['Service','Durability engineering'],['Environment','Aggressive marine exposure'],['Asset','Critical water infrastructure'],['Region','Fujairah, UAE']]}
};

Object.assign(projectData,{
  'trillionaire-residences':{title:'Trillionaire Residences',location:'Dubai, UAE',category:'assessment',image:'https://cde-me.com/wp-content/uploads/2026/03/Trillionaire_Residences_by_Binghatti_.jpg',summary:'Condition Assessment · Repair Design',lead:'Full structural condition survey of a luxury residential high-rise.',body:'CDE’s source portfolio records a full structural condition survey identifying active corrosion, spalling and carbonation-related deterioration mechanisms, followed by comprehensive repair specifications and cost planning.',points:[['Scope','Condition assessment'],['Deliverable','Repair design'],['Asset','Luxury residential high-rise'],['Region','Dubai, UAE']]},
  'serenia-residences':{title:'Serenia Residences',location:'Palm Jumeirah, Dubai',category:'repair',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-15.jpg',summary:'Corrosion Investigation · Rehabilitation',lead:'A CDE Middle East reference for corrosion investigation and rehabilitation.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Corrosion investigation'],['Service','Rehabilitation'],['Asset','Residential development'],['Region','Palm Jumeirah, Dubai']]},
  'injaz-building':{title:'Injaz Building',location:'Dubai, UAE',category:'assessment',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-13d.jpg',summary:'Forensic Investigation · Structural Analysis',lead:'A CDE Middle East reference for forensic investigation and structural analysis.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Forensic investigation'],['Service','Structural analysis'],['Asset','Building structure'],['Region','Dubai, UAE']]},
  'west-f5-building':{title:'West F5 Building',location:'Dubai, UAE',category:'strengthening',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-6a.jpg',summary:'Structural Assessment · Strengthening Design',lead:'A CDE Middle East reference for structural assessment and strengthening design.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Structural assessment'],['Service','Strengthening design'],['Asset','Existing building'],['Region','Dubai, UAE']]},
  'seawater-intake':{title:'Seawater Intake Pumping Station',location:'Fujairah, UAE',category:'durability',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-10.jpg',summary:'Durability Engineering · Marine Environment',lead:'A CDE Middle East reference for durability engineering in an aggressive marine environment.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Durability engineering'],['Exposure','Marine environment'],['Asset','Pumping station'],['Region','Fujairah, UAE']]},
  'al-khaleej-plaza':{title:'Al Khaleej Plaza Tower',location:'Sharjah, UAE',category:'repair',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-7.jpg',summary:'Repair Design · QA/QC Supervision',lead:'A CDE Middle East reference for repair design and QA/QC supervision.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Repair design'],['Service','QA/QC supervision'],['Asset','Tower'],['Region','Sharjah, UAE']]},
  'dewa-substation':{title:'DEWA Substation Complex',location:'Dubai, UAE',category:'durability',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-8.jpg',summary:'Durability Planning · New Structure',lead:'A CDE Middle East reference for durability planning of a new structure.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Durability planning'],['Stage','New structure'],['Asset','Substation complex'],['Region','Dubai, UAE']]},
  'saraya-tower':{title:'Saraya Tower',location:'Abu Dhabi, UAE',category:'assessment',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-2c.png',summary:'Thermographic Inspection · Condition Assessment',lead:'A CDE Middle East reference for thermographic inspection and condition assessment.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Thermographic inspection'],['Service','Condition assessment'],['Asset','Tower'],['Region','Abu Dhabi, UAE']]},
  'lusail-mixed-use':{title:'Lusail Mixed-Use Development',location:'Doha, Qatar',category:'strengthening',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-3.png',summary:'Structural Assessment · PT System Investigation',lead:'A CDE Middle East reference for structural assessment and PT system investigation.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Structural assessment'],['Service','PT system investigation'],['Asset','Mixed-use development'],['Region','Doha, Qatar']]},
  'al-faisaliah':{title:'Al Faisaliah Infrastructure',location:'Riyadh, Saudi Arabia',category:'durability',image:'https://cde-me.com/wp-content/uploads/2026/03/proj-4.png',summary:'Durability Assessment · Service Life Modelling',lead:'A CDE Middle East reference for durability assessment and service-life modelling.',body:'The supplied CDE project register identifies this assignment by location and service scope. Further technical case-study information is not published in the provided source files.',points:[['Scope','Durability assessment'],['Service','Service-life modelling'],['Asset','Infrastructure'],['Region','Riyadh, Saudi Arabia']]}
});

const projectSlugByTitle={'Trillionaire Residences':'trillionaire-residences','Serenia Residences':'serenia-residences','Injaz Building':'injaz-building','West F5 Building':'west-f5-building','Seawater Intake Pumping Station':'seawater-intake','Al Khaleej Plaza Tower':'al-khaleej-plaza','DEWA Substation Complex':'dewa-substation','Saraya Tower':'saraya-tower','Lusail Mixed-Use Development':'lusail-mixed-use','Al Faisaliah Infrastructure':'al-faisaliah'};
document.querySelectorAll('.portfolio-card, .projects .project').forEach(card => { const title=card.querySelector('h2,h3')?.textContent.trim(); const slug=projectSlugByTitle[title]; if(!slug)return; card.classList.add('is-linked'); card.dataset.category=projectData[slug].category; card.tabIndex=0; card.setAttribute('role','link'); card.setAttribute('aria-label',`View ${title} project`); const go=()=>window.location.href=`project-detail.html?project=${slug}`; card.addEventListener('click',go); card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')go();}); });

const filterBar=document.querySelector('.portfolio-filter');
if(filterBar){ const names=['all','assessment','repair','durability','strengthening']; filterBar.querySelectorAll('span').forEach((span,i)=>{ const button=document.createElement('button'); button.type='button'; button.textContent=span.textContent; button.dataset.filter=names[i]; if(i===0)button.classList.add('active'); span.replaceWith(button); }); filterBar.addEventListener('click',e=>{ const button=e.target.closest('button'); if(!button)return; filterBar.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button)); document.querySelectorAll('.portfolio-card').forEach(card=>card.classList.toggle('is-hidden',button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter)); }); }

const params=new URLSearchParams(window.location.search);
if(document.body.classList.contains('detail-page')&&!document.body.classList.contains('project-detail-page')){ const data=serviceData[params.get('service')]||serviceData['condition-assessment']; const words=data.title.split(' '); document.title=`${data.title} — CDE Engineering Services`; document.getElementById('detailCategory').textContent=data.category; document.getElementById('detailTitle').innerHTML=`${words.slice(0,-1).join(' ')}<br><em>${words.at(-1)}.</em>`; document.getElementById('detailSummary').textContent=data.summary; document.getElementById('detailLead').textContent=data.lead; document.getElementById('detailBody').textContent=data.body; document.getElementById('detailPoints').innerHTML=data.points.map(p=>`<div><b>${p[0]}</b><span>${p[1]}</span></div>`).join(''); }
if(document.body.classList.contains('project-detail-page')){ const data=projectData[params.get('project')]||projectData['trillionaire-residences']; document.title=`${data.title} — CDE Projects`; document.getElementById('projectHero').style.backgroundImage=`url('${data.image}')`; document.getElementById('projectLocation').textContent=data.location; const words=data.title.split(' '); document.getElementById('projectTitle').innerHTML=`${words.slice(0,-1).join(' ')}<br><em>${words.at(-1)}.</em>`; document.getElementById('projectSummary').textContent=data.summary; document.getElementById('projectLead').textContent=data.lead; document.getElementById('projectBody').textContent=data.body; document.getElementById('projectPoints').innerHTML=data.points.map(p=>`<div><b>${p[0]}</b><span>${p[1]}</span></div>`).join(''); }
